export default {
    "app": {
        "Home": "Inicio",
        "News": "Noticias",
        "Login": "Iniciar sesión",
        "Register": "Registrar cuenta",
        "Notifications": "Notificaciones",
        "Logout": "Cerrar sesión",
        "Wellcome": "Bienvenido a ",
        "DescriptionJB": "Este sitio tiene fines educativos para el aprendizaje personal del desarrollo en Laravel framework.",
        "Title_news": "Titulo de la noticia",
        "Search": "Ingrese el texto a buscar",
        "Search_button": "Buscar",
        "Posted": "Posteado por: ",
        "Date_post": "Posteado el: ",
        "Read_more": "Leer más",
        "No_news": "No hay noticias registradas",
        "Create_news": "Crear nueva noticia",
        "Insert_title_new": "Ingrese un titulo",
        "Body_news": "Cuerpo de la noticia",
        "Image_news": "Imagen de la noticia",
        "Image_footer": "* Solo ingresar imágenes",
        "Title_login": "Inicio de sesión",
        "Email": "Correo electrónico",
        "Password": "Contraseña",
        "Remember": "Recordarme",
        "Login_button": "Iniciar sesión",
        "Forget_password": "¿Olvidaste tu contraseña?",
        "Social_login": "También puedes iniciar sesión con tus redes sociales:",
        "Title_register": "Registro de usuario",
        "Name": "Nombre",
        "User": "Usuario",
        "Repeat_password": "Repita contraseña",
        "Register_button": "Registrar",
        "Reset_password": "Restablecer contraseña",
        "Password_reset_button": "Enviar link para restablecer contraseña",
        "Confirm_password": "Confirmar contraseña",
        "Search_title": "Resultados de la búsqueda",
        "Perfil": "Perfil de usuario",
        "Send_dm": "Enviar DM",
        "New_message": "Nuevo mensaje",
        "For": "Para",
        "Message": "Mensaje",
        "Close": "Cerrar",
        "Send_message": "Enviar mensaje",
        "Follow": "Seguir",
        "Unfollow": "No seguir",
        "Followers": "Seguidores",
        "Following": "Siguiendo",
        "Conversation": "Conversación con:",
        "Date": "Fecha",
        "Edit": "Editar",
        "Details": "Detalle",
        "Delete": "Eliminar",
        "Empty": "No existen registros"
    },
    "auth": {
        "failed": "Estas credenciales no coinciden con nuestros registros.",
        "throttle": "Demasiados intentos de acceso. Por favor intente nuevamente en {seconds} segundos."
    },
    "pagination": {
        "previous": "&laquo; Anterior",
        "next": "Siguiente &raquo;"
    },
    "passwords": {
        "password": "Las contraseñas deben coincidir y contener al menos 6 caracteres",
        "reset": "¡Tu contraseña ha sido restablecida!",
        "sent": "¡Te hemos enviado por correo el enlace para restablecer tu contraseña!",
        "token": "El token de recuperación de contraseña es inválido.",
        "user": "No podemos encontrar ningún usuario con ese correo electrónico."
    },
    "validation": {
        "accepted": "{attribute} debe ser aceptado.",
        "active_url": "{attribute} no es una URL válida.",
        "after": "{attribute} debe ser una fecha posterior a {date}.",
        "after_or_equal": "{attribute} debe ser una fecha posterior o igual a {date}.",
        "alpha": "{attribute} sólo debe contener letras.",
        "alpha_dash": "{attribute} sólo debe contener letras, números y guiones.",
        "alpha_num": "{attribute} sólo debe contener letras y números.",
        "array": "{attribute} debe ser un conjunto.",
        "before": "{attribute} debe ser una fecha anterior a {date}.",
        "before_or_equal": "{attribute} debe ser una fecha anterior o igual a {date}.",
        "between": {
            "numeric": "{attribute} tiene que estar entre {min} - {max}.",
            "file": "{attribute} debe pesar entre {min} - {max} kilobytes.",
            "string": "{attribute} tiene que tener entre {min} - {max} caracteres.",
            "array": "{attribute} tiene que tener entre {min} - {max} ítems."
        },
        "boolean": "El campo {attribute} debe tener un valor verdadero o falso.",
        "confirmed": "La confirmación de {attribute} no coincide.",
        "date": "{attribute} no es una fecha válida.",
        "date_format": "{attribute} no corresponde al formato {format}.",
        "different": "{attribute} y {other} deben ser diferentes.",
        "digits": "{attribute} debe tener {digits} dígitos.",
        "digits_between": "{attribute} debe tener entre {min} y {max} dígitos.",
        "dimensions": "Las dimensiones de la imagen {attribute} no son válidas.",
        "distinct": "El campo {attribute} contiene un valor duplicado.",
        "email": "{attribute} no es un correo válido",
        "exists": "{attribute} es inválido.",
        "file": "El campo {attribute} debe ser un archivo.",
        "filled": "El campo {attribute} es obligatorio.",
        "gt": {
            "numeric": "El campo {attribute} debe ser mayor que {value}.",
            "file": "El campo {attribute} debe tener más de {value} kilobytes.",
            "string": "El campo {attribute} debe tener más de {value} caracteres.",
            "array": "El campo {attribute} debe tener más de {value} elementos."
        },
        "gte": {
            "numeric": "El campo {attribute} debe ser como mínimo {value}.",
            "file": "El campo {attribute} debe tener como mínimo {value} kilobytes.",
            "string": "El campo {attribute} debe tener como mínimo {value} caracteres.",
            "array": "El campo {attribute} debe tener como mínimo {value} elementos."
        },
        "image": "{attribute} debe ser una imagen.",
        "in": "{attribute} es inválido.",
        "in_array": "El campo {attribute} no existe en {other}.",
        "integer": "{attribute} debe ser un número entero.",
        "ip": "{attribute} debe ser una dirección IP válida.",
        "ipv4": "{attribute} debe ser un dirección IPv4 válida",
        "ipv6": "{attribute} debe ser un dirección IPv6 válida.",
        "json": "El campo {attribute} debe tener una cadena JSON válida.",
        "lt": {
            "numeric": "El campo {attribute} debe ser menor que {value}.",
            "file": "El campo {attribute} debe tener menos de {value} kilobytes.",
            "string": "El campo {attribute} debe tener menos de {value} caracteres.",
            "array": "El campo {attribute} debe tener menos de {value} elementos."
        },
        "lte": {
            "numeric": "El campo {attribute} debe ser como máximo {value}.",
            "file": "El campo {attribute} debe tener como máximo {value} kilobytes.",
            "string": "El campo {attribute} debe tener como máximo {value} caracteres.",
            "array": "El campo {attribute} debe tener como máximo {value} elementos."
        },
        "max": {
            "numeric": "{attribute} no debe ser mayor a {max}.",
            "file": "{attribute} no debe ser mayor que {max} kilobytes.",
            "string": "{attribute} no debe ser mayor que {max} caracteres.",
            "array": "{attribute} no debe tener más de {max} elementos."
        },
        "mimes": "{attribute} debe ser un archivo con formato: {values}.",
        "mimetypes": "{attribute} debe ser un archivo con formato: {values}.",
        "min": {
            "numeric": "El tamaño de {attribute} debe ser de al menos {min}.",
            "file": "El tamaño de {attribute} debe ser de al menos {min} kilobytes.",
            "string": "{attribute} debe contener al menos {min} caracteres.",
            "array": "{attribute} debe tener al menos {min} elementos."
        },
        "not_in": "{attribute} es inválido.",
        "not_regex": "El formato del campo {attribute} no es válido.",
        "numeric": "{attribute} debe ser numérico.",
        "present": "El campo {attribute} debe estar presente.",
        "regex": "El formato de {attribute} es inválido.",
        "required": "El campo {attribute} es obligatorio.",
        "required_if": "El campo {attribute} es obligatorio cuando {other} es {value}.",
        "required_unless": "El campo {attribute} es obligatorio a menos que {other} esté en {values}.",
        "required_with": "El campo {attribute} es obligatorio cuando {values} está presente.",
        "required_with_all": "El campo {attribute} es obligatorio cuando {values} está presente.",
        "required_without": "El campo {attribute} es obligatorio cuando {values} no está presente.",
        "required_without_all": "El campo {attribute} es obligatorio cuando ninguno de {values} estén presentes.",
        "same": "{attribute} y {other} deben coincidir.",
        "size": {
            "numeric": "El tamaño de {attribute} debe ser {size}.",
            "file": "El tamaño de {attribute} debe ser {size} kilobytes.",
            "string": "{attribute} debe contener {size} caracteres.",
            "array": "{attribute} debe contener {size} elementos."
        },
        "string": "El campo {attribute} debe ser una cadena de caracteres.",
        "timezone": "El {attribute} debe ser una zona válida.",
        "unique": "{attribute} ya ha sido registrado.",
        "uploaded": "Subir {attribute} ha fallado.",
        "url": "El formato {attribute} es inválido.",
        "uuid": "El campo {attribute} debe ser un UUID válido.",
        "custom": {
            "password": {
                "min": "La {attribute} debe contener más de {min} caracteres"
            },
            "email": {
                "unique": "El {attribute} ya ha sido registrado."
            }
        },
        "attributes": {
            "name": "nombre",
            "username": "usuario",
            "email": "correo electrónico",
            "first_name": "nombre",
            "last_name": "apellido",
            "password": "contraseña",
            "password_confirmation": "confirmación de la contraseña",
            "city": "ciudad",
            "country": "país",
            "address": "dirección",
            "phone": "teléfono",
            "mobile": "móvil",
            "age": "edad",
            "sex": "sexo",
            "gender": "género",
            "year": "año",
            "month": "mes",
            "day": "día",
            "hour": "hora",
            "minute": "minuto",
            "second": "segundo",
            "title": "título",
            "content": "contenido",
            "body": "contenido",
            "description": "descripción",
            "excerpt": "extracto",
            "date": "fecha",
            "time": "hora",
            "subject": "asunto",
            "message": "mensaje"
        }
    }
}
